# Generated by Django 3.1.2 on 2020-10-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0002_auto_20201010_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Content',
        ),
    ]
