# Generated by Django 3.1.2 on 2020-10-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0003_auto_20201010_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Images'},
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='image',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
