# Generated by Django 3.1.2 on 2020-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0004_auto_20201010_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
