# Generated by Django 3.1.2 on 2020-10-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0006_auto_20201010_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.TextField(default='', max_length=30),
        ),
    ]
