# Generated by Django 3.1.2 on 2020-10-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
